# Generated by Django 6.0.7 on 2026-08-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='accounts_tr_user_id_b38c46_idx',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
